backend:
  name: test-repo
  login: false
media_folder: assets
collections:
  - label: Test
    name: test
    files:
      - file: test.yml
        name: test
        label: Test
        fields:
          - name: test_widget
            label: Test Widget
            widget: test